server.port: 9081

spring.cloud.stream:
  function.definition: eventProcessor;eventListenConsumer;eventEntityProcessor
  default-binder: kafka
  kafka:
    binder:
      brokers:
        - localhost:9092
      configuration:
        schema:
          registry:
            url: http://localhost:8081
    streams:
      binder:
        configuration:
          application:
            id: event-broker-processor
          schema:
            registry:
              url: http://localhost:8081
    bindings:
      eventEntityProcessor-in-0:
        consumer:
          configuration:
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
  bindings:
    eventProcessor-in-0:
      destination: pcfleischer.eventbroker.event_source
    eventProcessor-out-0:
      destination: pcfleischer.eventbroker.event_callback
    eventListenConsumer-in-0:
      destination: pcfleischer.eventbroker.event_source
    eventEntityProcessor-in-0:
      destination: events.public.event_entity