server.port: 9081

spring.cloud.stream:
  # local
  function.definition: eventProcessor;eventListenConsumer
  default-binder: kafka
  kafka.binder:
    brokers:
      - localhost:9092
  bindings:
    eventProcessor-in-0:
      destination: event-source
    eventProcessor-out-0:
      destination: event-callback
    eventListenConsumer-in-0:
      destination: event-source